import { L10n, loadCldr, setCulture } from '@syncfusion/ej2-base';
import * as cagregorian from './ca-gregorian.json';
import * as numbers from './numbers.json';
import * as loaderJson from './timeZoneNames.json';
import { Gantt,Toolbar, Selection, Edit, Filter  } from '@syncfusion/ej2-gantt';
import { GanttData } from './datasource.ts';
Gantt.Inject(Toolbar, Selection, Edit, Filter);
L10n.load({
  'de-DE': {
      "gantt": {
        "emptyRecord": "Keine Datensätze zum Anzeigen",
        "id": "ID",
        "name": "Name",
        "startDate": "Anfangsdatum",
        "endDate": "Enddatum",
        "duration": "Dauer",
        "progress": "Fortschritt",
        "dependency": "Abhängigkeit",
        "notes": "Anmerkungen",
        "baselineStartDate": "Basisstartdatum",
        "baselineEndDate": "Baseline-Enddatum",
        "baselineDuration": "Basisdauer",
        "constraintDate": "Einschränkung Datum",
        "constraintType": "Einschränkungstyp",
        "taskMode": "Aufgabenmodus",
        "changeScheduleMode": "Ändern Sie den Zeitplanmodus",
        "subTasksStartDate": "Startdatum der Unteraufgaben",
        "subTasksEndDate": "Unteraufgaben Enddatum",
        "scheduleStartDate": "Startdatum planen",
        "scheduleEndDate": "Enddatum planen",
        "auto": "Auto",
        "manual": "Handbuch",
        "type": "Art",
        "offset": "Versatz",
        "resourceName": "Ressourcen",
        "resourceID": "Ressourcen-ID",
        "day": "Tag",
        "hour": "Stunde",
        "minute": "Minute",
        "days": "Tage",
        "hours": "Stunden",
        "minutes": "Minuten",
        "generalTab": "Allgemeines",
        "customTab": "Benutzerdefinierte Spalten",
        "writeNotes": "Notizen schreiben",
        "addDialogTitle": "Neue Aufgabe",
        "editDialogTitle": "Aufgabeninformationen",
        "saveButton": "Speichern",
        "add": "Hinzufügen",
        "edit": "Bearbeiten",
        "update": "Aktualisieren",
        "delete": "Löschen",
        "cancel": "Abbrechen",
        "search": "Suchen",
        "task": " Aufgabe",
        "tasks": " Aufgaben",
        "zoomIn": "Hineinzoomen",
        "zoomOut": "Rauszoomen",
        "zoomToFit": "Zoomen, um anzupassen",
        "excelExport": "Excel-Export",
        "csvExport": "CSV-Export",
        "expandAll": "Alle erweitern",
        "collapseAll": "Alles einklappen",
        "nextTimeSpan": "Nächste Zeitspanne",
        "prevTimeSpan": "Vorherige Zeitspanne",
        "okText": "OK",
        "confirmDelete": "Möchten Sie den Datensatz wirklich löschen?",
        "from": "Von",
        "to": "Bis",
        "taskLink": "Task-Link",
        "lag": "Verzögerung",
        "start": "Start",
        "finish": "Fertig",
        "enterValue": "Geben Sie einen Wert ein",
        "cancelLink": "Abbrechen, den vorhandenen Link behalten",
        "removeLink": "Entfernen Sie den Link und verschieben Sie <b> {0} </b>, um auf <b> {1} </b> zu beginnen.",
        "removeConstraint": "Entfernen <b> \"{0}\" </b> Einschränkung der Aufgabe <b> \"{1}\" </b>",
        "preserveLink": "Bewegen Sie die <b> {0} </b>, um auf <b> {1} </b> zu starten und den Link zu behalten.",
        "removeDependency": "Entfernen Sie die Abhängigkeit von <b> \"{0}\" </b> zu <b> \"{1}\" </b>",
        "cancelChange": "Die Veränderung abbrechen und nichts tun",
        "validateEditing": "Bearbeitung validieren",
        "constraintConflicts": "Einschränkungen Konflikte",
        "constraintTypeAsSoonAsPossible": "So schnell wie möglich",
        "constraintTypeAsLateAsPossible": "So spät wie möglich",
        "constraintTypeMustStartOn": "Muss anfangen",
        "constraintTypeMustFinishOn": "Muss eingehen",
        "constraintTypeStartNoEarlierThan": "Starten Sie nicht früher als",
        "constraintTypeStartNoLaterThan": "Beginnen Sie spätestens später als",
        "constraintTypeFinishNoEarlierThan": "Abschließen nicht früher als",
        "constraintTypeFinishNoLaterThan": "Ende spät als",
        "taskBeforePredecessor_FS": "Sie haben '{0}' verschoben, um vor dem Ende von '{1}' zu beginnen, und die beiden Aufgaben sind miteinander verknüpft. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskAfterPredecessor_FS": "Sie haben '{0}' von '{1}' entfernt und die beiden Aufgaben sind miteinander verknüpft. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskBeforePredecessor_SS": "Sie haben '{0}' verschoben, um vor dem Start von '{1}' zu beginnen, und die beiden Aufgaben sind miteinander verknüpft. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskAfterPredecessor_SS": "Sie haben '{0}' verschoben, um nach dem Start von '{1}' zu beginnen, und die beiden Aufgaben sind miteinander verbunden. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskBeforePredecessor_FF": "Sie haben '{0}' verschoben, um den Vorgang zu beenden, bevor '{1}' abgeschlossen ist, und die beiden Aufgaben sind miteinander verknüpft. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskAfterPredecessor_FF": "Sie haben \"{0}\" nach \"{1}\" verschoben, um den Vorgang abzuschließen, und die beiden Aufgaben sind miteinander verknüpft. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskBeforePredecessor_SF": "Sie haben '{0}' von '{1}' zum Start verschoben und die beiden Aufgaben sind miteinander verbunden. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskAfterPredecessor_SF": "Sie haben '{0}' nach dem Start von '{1}' verschoben und die beiden Aufgaben sind miteinander verbunden. Infolgedessen können die Links nicht beachtet werden. Wählen Sie unten eine Aktion aus, die ausgeführt werden soll",
        "taskInformation": "Aufgabeninformationen",
        "deleteTask": "Aufgabe löschen",
        "deleteDependency": "Abhängigkeit löschen",
        "convert": "Konvertieren",
        "save": "Speichern",
        "above": "Über",
        "below": "Unten",
        "child": "Kind",
        "milestone": "Meilenstein",
        "toTask": "Zur Aufgabe",
        "toMilestone": "Zum Meilenstein",
        "eventMarkers": "Ereignismarker",
        "leftTaskLabel": "Linke Aufgabenbezeichnung",
        "rightTaskLabel": "Richtige Aufgabenbezeichnung",
        "timelineCell": "Timeline-Zelle",
        "confirmPredecessorDelete": "Möchten Sie den Abhängigkeitslink wirklich entfernen?",
        "unit": "Einheit",
        "work": "Arbeit",
        "taskType": "Aufgabentyp",
        "unassignedTask": "Nicht zugewiesene Aufgabe",
        "group": "Gruppe",
        "indent": "Einzug",
        "outdent": "Ausrücken",
        "segments": "Segmente",
        "splitTask": "Aufgabe teilen",
        "mergeTask": "Aufgabe zusammenführen",
        "left": "Links",
        "right": "Recht",
        "FF": "FF",
        "FS": "FS",
        "SF": "SF",
        "SS": "SS"
      },
      "grid": {
        "EmptyRecord": "Keine Datensätze zum Anzeigen",
        "True": "wahr",
        "False": "falsch",
        "InvalidFilterMessage": "Ungültige Filterdaten",
        "GroupDropArea": "Ziehen Sie eine Spaltenüberschrift hierher, um nach der Spalte zu gruppieren",
        "UnGroup": "Klicken Sie hier, um die Gruppierung aufzuheben",
        "GroupDisable": "Gruppierung ist für diese Spalte deaktiviert",
        "FilterbarTitle": "\"s Filterbalkenzelle",
        "EmptyDataSourceError": "Datenquelle darf beim ersten Laden nicht leer sein, da Spalten aus der Datenquelle automatisch generiert werden",
        "Add": "Hinzufügen",
        "Edit": "Bearbeiten",
        "Cancel": "Abbrechen",
        "Update": "Aktualisieren",
        "Delete": "Löschen",
        "Print": "Drucken",
        "Pdfexport": "PDF-Export",
        "Excelexport": "Excel-Export",
        "Wordexport": "Word-Export",
        "Csvexport": "CSV-Export",
        "Search": "Suchen",
        "Columnchooser": "Spalten",
        "Save": "Speichern",
        "Item": "Datensatz",
        "Items": "Datensätze",
        "EditOperationAlert": "Keine Datensätze zum Bearbeiten ausgewählt",
        "DeleteOperationAlert": "Keine Datensätze zum Löschen ausgewählt",
        "SaveButton": "Speichern",
        "OKButton": "OK",
        "CancelButton": "Abbrechen",
        "EditFormTitle": "Details von",
        "AddFormTitle": "Neuen Datensatz hinzufügen",
        "BatchSaveConfirm": "Möchten Sie die Änderungen wirklich speichern?",
        "BatchSaveLostChanges": "Nicht gespeicherte Änderungen gehen verloren. Sind Sie sicher, dass Sie fortfahren wollen?",
        "ConfirmDelete": "Möchten Sie den Datensatz wirklich löschen?",
        "CancelEdit": "Möchten Sie die Änderungen wirklich abbrechen?",
        "ChooseColumns": "Spalten auswählen",
        "SearchColumns": "Spalten durchsuchen",
        "Matchs": "Keine Treffer gefunden",
        "FilterButton": "Filtern",
        "ClearButton": "Löschen",
        "StartsWith": "Beginnt mit",
        "EndsWith": "Endet mit",
        "Contains": "Enthält",
        "Equal": "Gleich",
        "NotEqual": "Nicht gleich",
        "LessThan": "Weniger als",
        "LessThanOrEqual": "Weniger als oder gleich",
        "GreaterThan": "Grösser als",
        "GreaterThanOrEqual": "Grösser als oder gleich",
        "ChooseDate": "Wählen Sie ein Datum",
        "EnterValue": "Geben Sie den Wert ein",
        "Copy": "Kopieren",
        "Group": "Nach dieser Spalte gruppieren",
        "Ungroup": "Gruppierung nach dieser Spalte aufheben",
        "autoFitAll": "Autofit alle Spalten",
        "autoFit": "Autofit diese Spalte",
        "Export": "Export",
        "FirstPage": "Erste Seite",
        "LastPage": "Letzte Seite",
        "PreviousPage": "Vorherige Seite",
        "NextPage": "Nächste Seite",
        "SortAscending": "Aufsteigend sortieren",
        "SortDescending": "Absteigend sortieren",
        "EditRecord": "Datensatz bearbeiten",
        "DeleteRecord": "Datensatz löschen",
        "FilterMenu": "Filter",
        "SelectAll": "Alle auswählen",
        "Blanks": "Leerzeichen",
        "FilterTrue": "Wahr",
        "FilterFalse": "Falsch",
        "NoResult": "Keine Treffer gefunden",
        "ClearFilter": "Filter löschen",
        "NumberFilter": "Anzahl Filter",
        "TextFilter": "Textfilter",
        "DateFilter": "Datumsfilter",
        "DateTimeFilter": "Datums- und Uhrzeit-Filter",
        "MatchCase": "Gross- / Kleinschreibung",
        "Between": "Zwischen",
        "CustomFilter": "Benutzerdefinierte Filter",
        "CustomFilterPlaceHolder": "Geben Sie einen Wert ein",
        "CustomFilterDatePlaceHolder": "Wählen Sie ein Datum",
        "AND": "UND",
        "OR": "ODER",
        "ShowRowsWhere": "Zeilen anzeigen, in denen:",
        "In": "In",
        "NotIn": "Nicht in",
        "NotStartsWith": "beginnt nicht mit",
        "Like": "Wie",
        "NotEndsWith": "endet nicht mit",
        "NotContains": "enthält nicht",
        "IsNull": "Null",
        "NotNull": "nicht null",
        "IsEmpty": "leer",
        "IsNotEmpty": "nicht leer",
        "AddCurrentSelection": "Aktuelle Auswahl zum Filter hinzufügen",
        "UnGroupButton": "Klicken Sie hier, um die Gruppierung aufzuheben",
        "AutoFitAll": "Automatisch alle Spalten anpassen",
        "AutoFit": "Diese Spalte automatisch anpassen",
        "Clear": "Klar",
        "FilterMenuDialogARIA": "Menüdialog filtern",
        "ExcelFilterDialogARIA": "Excel-Filterdialog",
        "DialogEditARIA": "Dialog bearbeiten",
        "ColumnChooserDialogARIA": "Spaltenauswahl",
        "ColumnMenuDialogARIA": "Spaltenmenüdialog",
        "CustomFilterDialogARIA": "Benutzerdefinierter Filterdialog",
        "SortAtoZ": "Sortiere von A bis Z",
        "SortZtoA": "Z bis A sortieren",
        "SortByOldest": "Nach Ältesten sortieren",
        "SortByNewest": "Nach Neuesten sortieren",
        "SortSmallestToLargest": "Vom Kleinsten zum Größten sortieren",
        "SortLargestToSmallest": "Vom Größten zum Kleinsten sortieren",
        "Sort": "Sortieren",
        "FilterDescription": "Drücken Sie die Alt-Nach-unten-Taste, um das Filtermenü zu öffnen",
        "SortDescription": "Drücken Sie zum Sortieren die Eingabetaste",
        "ColumnMenuDescription": "Drücken Sie die Alt-Nach-unten-Taste, um das Spaltenmenü zu öffnen",
        "GroupDescription": "Drücken Sie zum Gruppieren die Strg-Leertaste",
        "ColumnHeader": " Spaltenüberschrift ",
        "TemplateCell": " ist eine Vorlagenzelle",
        "CommandColumnAria": "ist Spaltenüberschrift der Befehls-Spalte",
        "DialogEdit": "Dialog bearbeiten",
        "ClipBoard": "Zwischenablage",
        "GroupButton": "Gruppenschaltfläche",
        "UnGroupAria": "Schaltfläche zum Aufheben der Gruppierung",
        "GroupSeperator": "Trennzeichen für die gruppierten Spalten",
        "UnGroupIcon": "heben Sie die Gruppierung der gruppierten Spalte auf ",
        "GroupedSortIcon": "sortieren Sie die gruppierte Spalte ",
        "GroupedDrag": "Ziehen Sie die gruppierte Spalte",
        "GroupCaption": " ist eine Gruppenunterschriftszelle",
        "CheckBoxLabel": "Kontrollkästchen",
        "Expanded": "Erweitert",
        "Collapsed": "Zusammengebrochen",
        "SelectAllCheckbox": "Kontrollkästchen „Alle auswählen“.",
        "SelectRow": "Zeile auswählen",
        "AscendingText": "Aufsteigend",
        "DescendingText": "Absteigend",
        "NoneText": "Keine"
      },
    }
});
loadCldr(loaderJson,numbers,cagregorian);
setCulture('de-DE');


let gantt: Gantt = new Gantt({
    dataSource: GanttData,
    height: '450px',
    locale: 'de-DE',
    taskFields: {
        id: 'TaskID',
        name: 'TaskName',
        startDate: 'StartDate',
        duration: 'Duration',
        progress: 'Progress',
        parentID: 'ParentID'
    },
    toolbar: ['Add', 'Edit', 'Delete', 'Cancel'],
    editSettings: {
        allowAdding: true,
        allowEditing: true,
        allowDeleting: true,
        allowTaskbarEditing: true,
        showDeleteConfirmDialog: true
    },
    allowFiltering:true,
});
gantt.appendTo('#Gantt');