export let data = [
  {
    TaskID: 1,
    TaskName: 'Project Initiation',
    StartDate: new Date('04/02/2019'),
    EndDate: new Date('04/21/2019'),
    subtasks: [
      { TaskID: 2, TaskName: 'Identify Site location', StartDate: new Date('04/02/2019'), Duration: 4, Progress: 50 },
      { TaskID: 3, TaskName: 'Perform Soil test', StartDate: new Date('04/02/2019'), Duration: 4, Progress: 50 },
      { TaskID: 4, TaskName: 'Soil test approval', StartDate: new Date('04/02/2019'), Duration: 4, Progress: 50 },
    ]
  },
  {
    TaskID: 5,
    TaskName: 'Project Estimation',
    StartDate: new Date('04/02/2019'),
    EndDate: new Date('04/21/2019'),
    subtasks: [
      { TaskID: 6, TaskName: 'Develop floor plan for estimation', StartDate: new Date('04/04/2019'), Duration: 3, Progress: 50 },
      { TaskID: 7, TaskName: 'List materials', StartDate: new Date('04/04/2019'), Duration: 3, Progress: 50 },
      { TaskID: 8, TaskName: 'Estimation approval', StartDate: new Date('04/04/2019'), Duration: 3, Progress: 50 }
    ]
  },
];
export let timelineTemplateData = [
  {
    TaskID: 1,
    TaskName: 'Product Concept',
    StartDate: new Date('04/02/2019'),
    EndDate: new Date('04/21/2019'),
  },
  {
    TaskID: 2,
    TaskName: 'Defining the product and its usage',
    StartDate: new Date('04/02/2019'),
    Duration: 3,
    ParentID: 1,
    Progress: 30,
  },
  {
    TaskID: 3,
    TaskName: 'Defining target audience',
    StartDate: new Date('04/02/2019'),
    Duration: 3,
    ParentID: 1,
  },
  {
    TaskID: 4,
    TaskName: 'Prepare product sketch and notes',
    StartDate: new Date('04/02/2019'),
    Duration: 3,
    ParentID: 1,
    Predecessor: '2',
    Progress: 30,
  },
  {
    TaskID: 5,
    TaskName: 'Concept Approval',
    StartDate: new Date('04/02/2019'),
    Duration: 0,
    Predecessor: '3,4',
  },
  {
    TaskID: 6,
    TaskName: 'Market Research',
    StartDate: new Date('04/02/2019'),
    EndDate: new Date('04/21/2019'),
  },
  {
    TaskID: 7,
    TaskName: 'Demand Analysis',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
    ParentID: 6,
  },
  {
    TaskID: 8,
    TaskName: 'Customer strength',
    StartDate: new Date('04/04/2019'),
    Duration: 4,
    ParentID: 7,
    Predecessor: '5',
    Progress: 30,
  },
  {
    TaskID: 9,
    TaskName: 'Market opportunity analysis',
    StartDate: new Date('04/04/2019'),
    Duration: 4,
    ParentID: 7,
    Predecessor: '5',
  },

  {
    TaskID: 10,
    TaskName: 'Competitor Analysis',
    StartDate: new Date('04/04/2019'),
    Duration: 4,
    ParentID: 6,
    Predecessor: '7,8',
    Progress: 30,
  },
  {
    TaskID: 11,
    TaskName: 'Product strength analysis',
    StartDate: new Date('04/04/2019'),
    Duration: 4,
    ParentID: 6,
    Predecessor: '9',
  },
  {
    TaskID: 12,
    TaskName: 'Research complete',
    StartDate: new Date('04/04/2019'),
    Duration: 0,
    ParentID: 6,
    Predecessor: '10',
  },

  {
    TaskID: 13,
    TaskName: 'Product Design and Development',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
  },
  {
    TaskID: 14,
    TaskName: 'Functionality design',
    StartDate: new Date('04/04/2019'),
    Duration: 7,
    Progress: 30,
    ParentID: 13,
  },
  {
    TaskID: 15,
    TaskName: 'Quality design',
    StartDate: new Date('04/04/2019'),
    Duration: 5,
    ParentID: 13,
  },
  {
    TaskID: 16,
    TaskName: 'Define Reliability',
    StartDate: new Date('04/04/2019'),
    Duration: 5,
    Progress: 30,
    ParentID: 13,
  },
  {
    TaskID: 17,
    TaskName: 'Identifying raw materials ',
    StartDate: new Date('04/04/2019'),
    Duration: 4,
    ParentID: 13,
  },
  {
    TaskID: 18,
    TaskName: 'Define cost plan',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
    ParentID: 13,
  },
  {
    TaskID: 19,
    TaskName: 'Manufacturing cost',
    StartDate: new Date('04/04/2019'),
    Duration: 1,
    ParentID: 18,
    Progress: 30,
  },
  {
    TaskID: 20,
    TaskName: 'Selling cost',
    StartDate: new Date('04/04/2019'),
    Duration: 1,
    ParentID: 18,
  },
  {
    TaskID: 21,
    TaskName: 'Development of the final design',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
    ParentID: 13,
  },
  {
    TaskID: 22,
    TaskName: 'Defining dimensions and package volume',
    StartDate: new Date('04/04/2019'),
    Duration: 2,
    ParentID: 21,
    Progress: 30,
  },
  {
    TaskID: 23,
    TaskName: 'Develop design to meet industry standards',
    StartDate: new Date('04/04/2019'),
    Duration: 3,
    ParentID: 21,
  },
  {
    TaskID: 24,
    TaskName: 'Include all the details',
    StartDate: new Date('04/04/2019'),
    Duration: 5,
    ParentID: 21,
  },
  {
    TaskID: 25,
    TaskName: 'CAD Computer-aided design',
    StartDate: new Date('04/04/2019'),
    Duration: 10,
    Progress: 30,
    ParentID: 13,
  },
  {
    TaskID: 26,
    TaskName: 'CAM Computer-aided manufacturing',
    StartDate: new Date('04/04/2019'),
    Duration: 10,
    ParentID: 13,
  },
  {
    TaskID: 27,
    TaskName: 'Prototype Testing',
    StartDate: new Date('04/04/2019'),
    Duration: 12,
    Progress: 30,
  },
  {
    TaskID: 28,
    TaskName: 'Include feedback',
    StartDate: new Date('04/04/2019'),
    Duration: 5,
  },
  {
    TaskID: 29,
    TaskName: 'Manufacturing',
    StartDate: new Date('04/04/2019'),
    Duration: 9,
    Progress: 30,
  },
  {
    TaskID: 30,
    TaskName: 'Assembling materials to finished goods',
    StartDate: new Date('04/04/2019'),
    Duration: 12,
  },
  {
    TaskID: 31,
    TaskName: 'Feedback and Testing',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
  },
  {
    TaskID: 32,
    TaskName: 'Internal testing and feedback',
    StartDate: new Date('04/04/2019'),
    Duration: 5,
    ParentID: 31,
    Progress: 30,
  },
  {
    TaskID: 33,
    TaskName: 'Customer testing and feedback',
    StartDate: new Date('04/04/2019'),
    Duration: 7,
    ParentID: 31,
    Progress: 30,
  },
  {
    TaskID: 34,
    TaskName: 'Product Development',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
  },
  {
    TaskID: 35,
    TaskName: 'Important improvements',
    StartDate: new Date('04/04/2019'),
    Duration: 2,
    ParentID: 34,
    Progress: 30,
  },
  {
    TaskID: 36,
    TaskName: 'Address any unforeseen issues',
    StartDate: new Date('04/04/2019'),
    Duration: 2,
    ParentID: 34,
    Progress: 30,
  },
  {
    TaskID: 37,
    TaskName: 'Final Product',
    StartDate: new Date('04/04/2019'),
    EndDate: new Date('04/21/2019'),
  },
  {
    TaskID: 38,
    TaskName: 'Branding product',
    StartDate: new Date('04/04/2019'),
    Duration: 5,
    ParentID: 37,
  },
  {
    TaskID: 39,
    TaskName: 'Marketing and pre-sales',
    StartDate: new Date('04/04/2019'),
    Duration: 10,
    ParentID: 37,
    Progress: 30,
  },
];
